version: "3"
services:
  web:
    build: .
    environment:
      - NODE_ENV=developement
      - MYSQL_DATABASE_URL=mysql://DB_user:DB_password@mysql:3306/DB_resizer
    ports:
      - 1337:1337
    command: "npm run dev"
    volumes:
      - ./:/app
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=DB_resizer
      - MYSQL_USER=DB_user
      - MYSQL_PASSWORD=DB_password
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    volumes:
      - ./_docker/mysql:/var/lib/mysql
